# Generated by Django 3.2.4 on 2022-06-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0002_missionindicator_missionindicatorcatogery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionIndicatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='missionindicator',
            name='mission',
        ),
        migrations.DeleteModel(
            name='MissionIndicatorCatogery',
        ),
        migrations.AddField(
            model_name='missionindicator',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.missionindicatorcategory'),
            preserve_default=False,
        ),
    ]
