# Generated by Django 3.2.4 on 2022-06-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0003_auto_20220627_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='missionindicator',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='missionindicatorcategory',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
