# Generated by Django 3.2.4 on 2022-06-29 04:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0004_auto_20220628_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_template',
            field=models.IntegerField(choices=[(1, 'Indicator'), (2, 'Form')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('field_name', models.CharField(max_length=350)),
                ('field_type', models.IntegerField(choices=[(1, 'Text'), (2, 'Radio'), (3, 'Number'), (4, 'File Upload'), (5, 'Date')])),
                ('required', models.BooleanField(default=True)),
                ('field_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
