# Generated by Django 3.2.4 on 2022-07-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0005_auto_20220629_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionForm',
            new_name='MissionQuestion',
        ),
        migrations.CreateModel(
            name='MissionQuastionChioce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('report_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mission_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.missionquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
