# Generated by Django 3.2.4 on 2022-07-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_master', '0007_missionindicator_indicator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='district',
        ),
        migrations.AlterField(
            model_name='missionindicator',
            name='indicator_type',
            field=models.IntegerField(choices=[(1, 'Gender Base'), (2, 'Total')], default=1),
        ),
        migrations.CreateModel(
            name='VisionCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.district')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPartnerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('partner', 'user')},
            },
        ),
    ]
