# Generated by Django 3.2.4 on 2022-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0009_alter_missionquestion_field_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name_plural': 'Donor'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name_plural': 'Mission'},
        ),
        migrations.AlterModelOptions(
            name='missionindicator',
            options={'verbose_name_plural': 'Mission Indicator'},
        ),
        migrations.AlterModelOptions(
            name='missionindicatorcategory',
            options={'verbose_name_plural': 'Mission Indicator Category'},
        ),
        migrations.AlterModelOptions(
            name='missionquastionchioce',
            options={'verbose_name_plural': 'Mission Quastion Chioce'},
        ),
        migrations.AlterModelOptions(
            name='missionquestion',
            options={'verbose_name_plural': 'Mission Question'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partner'},
        ),
        migrations.AlterModelOptions(
            name='partnermissionmapping',
            options={'verbose_name_plural': 'Partner Mission Mapping'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='userpartnermapping',
            options={'verbose_name_plural': 'User Partner Mapping'},
        ),
        migrations.AlterModelOptions(
            name='visioncentre',
            options={'verbose_name_plural': 'Vision Centre'},
        ),
        migrations.AddField(
            model_name='mission',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='missionindicatorcategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Program Indicator'), (2, 'Finace Indicator'), (3, 'Income & Expense')], default=1),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
