# Generated by Django 3.2.4 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0010_auto_20220706_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
        migrations.AlterField(
            model_name='missionindicatorcategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Program Indicator'), (2, 'Finance Indicator')], default=1),
        ),
    ]
