# Generated by Django 3.2.4 on 2022-07-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application_master', '0012_missionindicatortarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='SEO friendly url, use only aplhabets and hyphen')),
                ('backend_link', models.CharField(blank=True, max_length=512)),
                ('icon', models.CharField(blank=True, max_length=512)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('inner_display', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.menus')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'ordering': ('menu_order',),
            },
        ),
    ]
