# Generated by Django 3.2.4 on 2022-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0013_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
