# Generated by Django 3.2.4 on 2022-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0014_alter_mission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
