# Generated by Django 3.2.4 on 2022-07-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application_master', '0015_alter_partner_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('upload_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Facility Files',
            },
        ),
        migrations.CreateModel(
            name='PartnerMissionDonorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Partner Mission Donor Mapping',
            },
        ),
        migrations.RemoveField(
            model_name='missionquestion',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='partnermissionmapping',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='partnermissionmapping',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='visioncentre',
            name='district',
        ),
        migrations.RemoveField(
            model_name='visioncentre',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='visioncentre',
            name='partner',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='backend_link',
            new_name='app_link',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='Date_of_association',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='inner_display',
        ),
        migrations.AlterField(
            model_name='district',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image_folder/'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='menus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_template',
            field=models.IntegerField(choices=[(1, 'Indicator'), (2, 'Form')], default=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='missionindicator',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='missionindicatorcategory',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='mission_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.missionindicator'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='userpartnermapping',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='userpartnermapping',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MissionQuastionChioce',
        ),
        migrations.DeleteModel(
            name='MissionQuestion',
        ),
        migrations.DeleteModel(
            name='PartnerMissionMapping',
        ),
    ]
