# Generated by Django 3.2.4 on 2022-07-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0009_auto_20220713_0931'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_master', '0016_auto_20220713_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisionCentre',
        ),
        migrations.AddField(
            model_name='partnermissiondonormapping',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.donor'),
        ),
        migrations.AddField(
            model_name='partnermissiondonormapping',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission'),
        ),
        migrations.AddField(
            model_name='partnermissiondonormapping',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partner'),
        ),
        migrations.AddField(
            model_name='facilityfiles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityfiles',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_master.facility'),
        ),
        migrations.AddField(
            model_name='facilityfiles',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.district'),
        ),
        migrations.AddField(
            model_name='facility',
            name='partner_mission_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partnermissiondonormapping'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('name', 'partner_mission_mapping')},
        ),
    ]
