# Generated by Django 3.2.4 on 2022-07-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0017_auto_20220713_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityfiles',
            name='name',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionindicatortarget',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.facility'),
        ),
    ]
