# Generated by Django 3.2.4 on 2022-07-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0019_auto_20220718_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMissionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Partner Mission Mapping',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=350)),
                ('upload_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Project Files',
            },
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facility',
            name='district',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='partner_mission_donor_mapping',
        ),
        migrations.RemoveField(
            model_name='facilityfiles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='facilityfiles',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityfiles',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='partnermissiondonormapping',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='partnermissiondonormapping',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='partnermissiondonormapping',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='missionindicatortarget',
            name='facility',
        ),
        migrations.AlterField(
            model_name='missionindicatorcategory',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission'),
        ),
        migrations.CreateModel(
            name='ProjectDonorMapping',
            fields=[
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='application_master.project')),
            ],
            options={
                'verbose_name_plural': 'Project Donor Mapping',
            },
        ),
    ]
