# Generated by Django 3.2.4 on 2022-07-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0020_auto_20220718_1348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0013_auto_20220718_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityFiles',
        ),
        migrations.DeleteModel(
            name='PartnerMissionDonorMapping',
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.district'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_mission_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partnermissionmapping'),
        ),
        migrations.AddField(
            model_name='partnermissionmapping',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.mission'),
        ),
        migrations.AddField(
            model_name='partnermissionmapping',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.partner'),
        ),
        migrations.AddField(
            model_name='missionindicatortarget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project'),
        ),
        migrations.AddField(
            model_name='projectdonormapping',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.donor'),
        ),
    ]
