# Generated by Django 3.2.4 on 2022-07-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0021_auto_20220718_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'partner_mission_mapping')},
        ),
    ]
