# Generated by Django 3.2.4 on 2022-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0022_alter_project_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='icon',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
