# Generated by Django 3.2.4 on 2022-07-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0023_menus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
