# Generated by Django 3.2.4 on 2022-07-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0024_mission_short_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionindicatorcategory',
            unique_together={('name', 'mission')},
        ),
    ]
