# Generated by Django 3.2.4 on 2022-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0025_alter_missionindicatorcategory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionindicator',
            name='indicator_type',
            field=models.IntegerField(choices=[(1, 'Gender Base'), (2, 'Total'), (3, 'Actuals'), (4, 'Actuals With Grants Received')], default=1),
        ),
    ]
