# Generated by Django 3.2.4 on 2022-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0026_alter_missionindicator_indicator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
