# Generated by Django 3.2.4 on 2022-07-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0027_project_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionindicator',
            options={'ordering': ['name'], 'verbose_name_plural': 'Mission Indicator'},
        ),
    ]
