# Generated by Django 3.2.4 on 2022-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0028_alter_missionindicator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionindicatorcategory',
            name='label_configuration',
            field=models.IntegerField(default=1),
        ),
    ]
