# Generated by Django 3.2.4 on 2022-08-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0029_missionindicatorcategory_label_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionindicatorcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Mission Indicator Category'},
        ),
    ]
