# Generated by Django 3.2.4 on 2022-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0031_auto_20220809_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
