# Generated by Django 3.2.4 on 2022-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0032_auto_20220822_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
