# Generated by Django 3.2.4 on 2022-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0034_alter_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='age_group_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to='image_folder/'),
        ),
    ]
