# Generated by Django 3.2.4 on 2022-08-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0035_auto_20220823_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name_plural': '         District'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('name',), 'verbose_name_plural': '  Donor'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('name',), 'verbose_name_plural': '        Mission'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',), 'verbose_name_plural': '         Partner'},
        ),
        migrations.AlterModelOptions(
            name='partnermissionmapping',
            options={'ordering': ('partner__name',), 'verbose_name_plural': '     Partner Mission Mapping'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name_plural': '    Project'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'verbose_name_plural': '          State'},
        ),
    ]
