# Generated by Django 3.2.4 on 2022-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0041_userprojectmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionindicatortarget',
            name='periodicity_date',
        ),
        migrations.AddField(
            model_name='missionindicatortarget',
            name='approved_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionindicatortarget',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
