# Generated by Django 3.2.4 on 2024-05-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0042_auto_20221018_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name_plural': '            District'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('name',), 'verbose_name_plural': '     Donor'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('name',), 'verbose_name_plural': '           Mission'},
        ),
        migrations.AlterModelOptions(
            name='missionindicator',
            options={'ordering': ['name'], 'verbose_name_plural': '       Mission Indicator'},
        ),
        migrations.AlterModelOptions(
            name='missionindicatorcategory',
            options={'ordering': ['name'], 'verbose_name_plural': '        Mission Indicator Category'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',), 'verbose_name_plural': '          Partner'},
        ),
        migrations.AlterModelOptions(
            name='partnermissionmapping',
            options={'ordering': ('partner__name',), 'verbose_name_plural': '         Partner Mission Mapping'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name_plural': '      Project'},
        ),
        migrations.AlterModelOptions(
            name='projectdonormapping',
            options={'verbose_name_plural': '    Project Donor Mapping'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'verbose_name_plural': '             State'},
        ),
        migrations.AlterModelOptions(
            name='userpartnermapping',
            options={'verbose_name_plural': '  User Partner Mapping'},
        ),
        migrations.AlterModelOptions(
            name='userprojectmapping',
            options={'verbose_name_plural': ' User Project Mapping'},
        ),
        migrations.AlterField(
            model_name='missionindicatorcategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Programme Indicator'), (2, 'Finance Indicator')], default=1),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='mission_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.missionindicator',blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project',blank=True, null=True),
        ),
    ]
