# Generated by Django 3.2.4 on 2024-06-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('application_master', '0043_auto_20240509_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionindicatortarget',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='missionindicatortarget',
            name='target',
        ),
        migrations.AlterField(
            model_name='missionindicatortarget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project'),
        ),
        migrations.CreateModel(
            name='MasterLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('code', models.IntegerField(default=0)),
                ('order', models.FloatField(blank=True, default=0, null=True)),
                ('choice_id', models.IntegerField(default=0)),
                ('skip_question', models.JSONField(blank=True, default=list, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.masterlookup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoundaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.boundarylevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('boundary_level', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('_polypoints', models.CharField(blank=True, default='[]', max_length=500, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('udf1', models.PositiveIntegerField(default=0)),
                ('short_code', models.CharField(max_length=100, verbose_name='Short Code')),
                ('boundary_level_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.boundarylevel')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.boundary')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterlookup_boundary_region', to='application_master.masterlookup')),
                ('ward_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterlookup_ward', to='application_master.masterlookup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
