# Generated by Django 4.2.13 on 2024-07-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0044_auto_20240618_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarylevel',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.DeleteModel(
            name='BoundaryLevel',
        ),
    ]
