# Generated by Django 4.2.13 on 2024-06-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application_master', '0044_auto_20240618_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarylevel',
            name='parent',
        ),
        migrations.AlterField(
            model_name='menus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.DeleteModel(
            name='BoundaryLevel',
        ),
    ]
