# Generated by Django 4.2.13 on 2024-06-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application_master", "0044_auto_20240618_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="masterlookup_application",
                to="application_master.masterlookup",
            ),
        ),
    ]
