# Generated by Django 4.2.13 on 2024-06-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application_master', '0045_remove_boundarylevel_parent_alter_menus_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='group',
        ),
        migrations.AddField(
            model_name='menus',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
