# Generated by Django 4.2.13 on 2024-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_master", "0049_missionindicatortarget_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
