# Generated by Django 4.2.13 on 2024-07-09 12:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application_master", "0045_project_application_type"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboard", "0003_dashboardindicatorfilter_dashboardwidgettypes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.PositiveIntegerField(
                        choices=[(2, "Active"), (0, "Inactive")], default=2
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("listing_order", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                ("remark", models.CharField(max_length=500)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.PositiveIntegerField(
                        choices=[(2, "Active"), (0, "Inactive")], default=2
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("listing_order", models.PositiveIntegerField(default=0)),
                ("month", models.IntegerField(verbose_name="Month(YYYYMM)")),
                (
                    "children_covered_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("children_covered_count", models.IntegerField(default=0)),
                (
                    "school_covered_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("school_covered_count", models.IntegerField(default=0)),
                (
                    "teachers_train_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("teachers_train_count", models.IntegerField(default=0)),
                (
                    "children_pres_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("children_pres_count", models.IntegerField(default=0)),
                (
                    "child_prov_spec_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("child_prov_spec_count", models.IntegerField(default=0)),
                (
                    "pgp_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("pgp_count", models.IntegerField(default=0)),
                (
                    "children_reffered_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("children_referred_count", models.IntegerField(default=0)),
                (
                    "child_prov_hos_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("child_prov_hos_count", models.IntegerField(default=0)),
                (
                    "children_adv_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("children_adv_count", models.IntegerField(default=0)),
                (
                    "children_prov_sgy_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("children_prov_sgy_count", models.IntegerField(default=0)),
                (
                    "swc_uuid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=75),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
                ("swc_count", models.IntegerField(default=0)),
                (
                    "current_status",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted for Approval"),
                            (2, "submitted for Project In-charge"),
                            (3, "Approved"),
                            (4, "Rejected"),
                        ],
                        default=0,
                    ),
                ),
                ("partner_submitted", models.DateField(blank=True, null=True)),
                ("project_incharge_submitted", models.DateField(blank=True, null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application_master.partner",
                    ),
                ),
                (
                    "partner_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_incharge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_entry_operator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
