# Generated by Django 4.2.13 on 2024-07-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remarks_monthlydashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlydashboard",
            name="creation_key",
            field=models.CharField(default=None, max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
