# Generated by Django 4.2.13 on 2024-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_monthlydashboard_child_prov_hos_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydashboard',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'Submitted for Approval'), (2, 'Submitted for Project In-charge'), (3, 'Submitted for Admin'), (4, 'Approved'), (5, 'Rejected')], default=0),
        ),
    ]
