# Generated by Django 4.2.13 on 2024-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_monthlydashboard_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('chart_type', models.IntegerField(blank=True, choices=[(1, 'Column Chart'), (2, 'Pie Chart'), (3, 'Table Chart'), (4, 'Bar Chart'), (5, 'Column Stack'), (6, 'Bar Dynamic Chart'), (7, 'Column Dynamic Stack'), (8, 'Card chart'), (9, 'Html Table Chart'), (10, 'Line chart'), (12, 'Dounut chart'), (13, 'Html Table Chart Dynmaic'), (14, 'Custom Html Table Chart')], help_text='1=Column Chart, 2=Pie Chart, 3=Table Chart, 4=Bar Chart, 5=Column Stack, 6=Bar Dynamic Chart, 7=Column Dynamic Stack, 8=Card Chart, 9=Geo chart,10=Line chart,11=Progressive Line, 12=Dounut chart', null=True)),
                ('chart_slug', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('page_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('chart_title', models.CharField(blank=True, max_length=500, null=True)),
                ('vertical_axis_title', models.CharField(blank=True, max_length=200, null=True)),
                ('horizontal_axis_title', models.CharField(blank=True, max_length=200, null=True)),
                ('chart_note', models.TextField(blank=True, null=True)),
                ('chart_tooltip', models.TextField(blank=True, null=True)),
                ('chart_height', models.TextField(blank=True, help_text='Chart height in pixel or %', null=True)),
                ('click_handler', models.JSONField(blank=True, help_text='json text to set the handler options: {on_click_handler:function-name, url_template:url with placeholders for chart element(bar/column) key value', null=True)),
                ('chart_options', models.JSONField(blank=True, help_text='json text to set the chart options', null=True)),
                ('div_class', models.TextField(blank=True, help_text='div class name to be used for the chart container - ex:col-md-6, col-md-12 etc', null=True)),
                ('chart_query', models.JSONField(blank=True, help_text='sql query and related filter details as json - with keys sqlquery, filters and etc', null=True)),
                ('display_order', models.IntegerField(blank=True, help_text='order in which the charts have to be displayed', null=True)),
                ('filter_info', models.JSONField(blank=True, help_text='report filters meta data in json format', null=True)),
            ],
            options={
                'verbose_name_plural': 'Chart Meta',
            },
        ),
    ]
