# Generated by Django 4.2.13 on 2024-09-16 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_load_dashboard_data_create_table"),
        ("dashboard", "0010_remove_monthlydashboard_month_and_more"),
    ]

    operations = []
