# Generated by Django 4.2.15 on 2024-09-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_merge_20240902_1204'),
        ('dashboard', '0011_merge_20240916_1624'),
    ]

    operations = [
    ]
