# Generated by Django 3.2.4 on 2022-05-17 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'No'), (2, 'Yes')], db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('report_slug', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed.')])),
                ('report_title', models.CharField(blank=True, max_length=500, null=True)),
                ('report_header', models.JSONField(blank=True, help_text='report headers in json format', null=True)),
                ('report_query', models.JSONField(blank=True, help_text='sql query and related filter details as json - with keys sqlquery, filters and etc', null=True)),
                ('display_order', models.IntegerField(blank=True, help_text='order in which the charts have to be displayed', null=True)),
                ('filter_info', models.JSONField(blank=True, help_text='report filters meta data in json format', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdreports_reportmeta_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiedreports_reportmeta_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report Meta',
            },
        ),
    ]
