# Generated by Django 3.2.4 on 2022-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmeta',
            name='sort_info',
            field=models.JSONField(blank=True, help_text='report sort meta data in json format', null=True),
        ),
    ]
