# Generated by Django 3.2.4 on 2022-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220620_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmeta',
            name='custom_export_header',
            field=models.JSONField(blank=True, help_text='custom headers for excel export to handle multilevel headers in json format', null=True),
        ),
    ]
