# Generated by Django 3.2.4 on 2022-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportmeta_custom_export_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmeta',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reportmeta',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='reportmeta',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportmeta',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='reportmeta',
            name='listing_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportmeta',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
    ]
