# Generated by Django 4.2.13 on 2024-07-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0047_userprofile'),
        ('reports', '0007_auto_20221106_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuietlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('academic_year', models.IntegerField()),
                ('annual_direct', models.IntegerField()),
                ('q1_direct', models.IntegerField(default=0)),
                ('q2_direct', models.IntegerField(default=0)),
                ('q3_direct', models.IntegerField(default=0)),
                ('q4_direct', models.IntegerField(default=0)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.masterlookup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project')),
            ],
            options={
                'unique_together': {('project', 'indicator', 'annual_direct')},
            },
        ),
    ]
