# Generated by Django 4.2.13 on 2024-07-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0047_userprofile'),
        ('reports', '0008_quietlyreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quietlyreport',
            old_name='annual_direct',
            new_name='annual_target',
        ),
        migrations.RenameField(
            model_name='quietlyreport',
            old_name='q1_direct',
            new_name='q1_target',
        ),
        migrations.RenameField(
            model_name='quietlyreport',
            old_name='q2_direct',
            new_name='q2_target',
        ),
        migrations.RenameField(
            model_name='quietlyreport',
            old_name='q3_direct',
            new_name='q3_target',
        ),
        migrations.RenameField(
            model_name='quietlyreport',
            old_name='q4_direct',
            new_name='q4_target',
        ),
        migrations.AlterUniqueTogether(
            name='quietlyreport',
            unique_together={('project', 'indicator', 'academic_year')},
        ),
    ]
