# Generated by Django 4.2.13 on 2024-08-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_annual_direct_quietlyreport_annual_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('academic_year', models.IntegerField()),
                ('annual_target', models.IntegerField()),
                ('q1_target', models.IntegerField(default=0)),
                ('q2_target', models.IntegerField(default=0)),
                ('q3_target', models.IntegerField(default=0)),
                ('q4_target', models.IntegerField(default=0)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.masterlookup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project')),
            ],
            options={
                'unique_together': {('project', 'indicator', 'academic_year')},
            },
        ),
    ]
