# Generated by Django 3.2.4 on 2022-07-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0008_auto_20220705_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0002_auto_20220704_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionresponse',
            name='response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='MissionIndicatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('response', jsonfield.fields.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_master.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
