# Generated by Django 3.2.4 on 2022-07-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0010_auto_20220706_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0003_auto_20220705_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionindicatortarget',
            options={'verbose_name_plural': 'Mission Indicator Target'},
        ),
        migrations.AlterModelOptions(
            name='missionresponse',
            options={'verbose_name_plural': 'Mission Indicator Achievement'},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_status', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('extension_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vision_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_master.visioncentre')),
            ],
            options={
                'verbose_name_plural': 'Mission Indicator Target',
            },
        ),
        migrations.CreateModel(
            name='MissionIndicatorAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Deleted'), (2, 'Active'), (3, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('interface', models.CharField(choices=[('0', 'Web'), ('1', 'App'), ('2', 'Migrated Data')], default=0, max_length=2)),
                ('response', jsonfield.fields.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_master.mission')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Mission Indicator Achievement',
            },
        ),
    ]
