# Generated by Django 3.2.4 on 2022-07-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_auto_20220706_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionResponse',
        ),
    ]
