# Generated by Django 3.2.4 on 2022-07-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0006_missionres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionRes',
        ),
    ]
