# Generated by Django 3.2.4 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0007_delete_missionres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Task'},
        ),
        migrations.RemoveField(
            model_name='missionindicatorachievement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='missionindicatorachievement',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='missionindicatorachievement',
            name='mission',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Submitted for approval'), (3, 'Approved'), (4, 'Rejected'), (5, 'Cancelled')], default=1),
        ),
        migrations.DeleteModel(
            name='MissionIndicatorTarget',
        ),
    ]
