# Generated by Django 3.2.4 on 2022-07-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0016_auto_20220713_0931'),
        ('mis', '0008_auto_20220707_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Task'},
        ),
        migrations.AlterField(
            model_name='missionindicatorachievement',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='missionindicatorachievement',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='vision_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.facility'),
        ),
    ]
