# Generated by Django 3.2.4 on 2022-07-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0010_rename_vision_centre_task_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='facility',
        ),
    ]
