# Generated by Django 3.2.4 on 2022-07-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0017_auto_20220713_0931'),
        ('mis', '0011_remove_task_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.facility'),
        ),
    ]
