# Generated by Django 3.2.4 on 2022-07-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_master', '0020_auto_20220718_1348'),
        ('mis', '0012_task_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='facility',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_master.project'),
        ),
    ]
