# Generated by Django 3.2.4 on 2022-07-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0013_auto_20220718_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionindicatorachievement',
            name='number_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionindicatorachievement',
            name='project_reference_file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d'),
        ),
    ]
