# Generated by Django 3.2.4 on 2022-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0014_auto_20220721_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name_plural': ' Task'},
        ),
    ]
