# Generated by Django 3.2.4 on 2022-09-02 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0016_missionindicatorachievement_camp_organized'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='task_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
