# Generated by Django 3.2.4 on 2022-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0017_auto_20220902_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Submitted for Partner Admin'), (3, 'Submitted for Project In-charge'), (4, 'Approved'), (5, 'Rejected')], default=1),
        ),
    ]
