# Generated by Django 3.2.4 on 2024-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0020_task_task_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Task'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Pending data entry'), (2, 'Submitted for Partner Admin'), (3, 'Submitted for Project In-charge'), (4, 'Approved'), (5, 'Rejected')], default=1),
        ),
    ]
