# Generated by Django 4.2.13 on 2024-06-20 04:50

from django.db import migrations, models
from django.db.models import F

def update_usernames_to_lowercase(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    users = User.objects.all()
    for user in users:
        user.username = user.username.lower()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_usernames_to_lowercase),
    ]