# Generated by Django 3.2.4 on 2024-06-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20240620_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLanguageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(2, 'Active'), (0, 'Inactive')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('listing_order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('other_text', models.CharField(blank=True, max_length=255, null=True)),
                ('integer_field', models.IntegerField(default=0)),
                ('applabel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.applabel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
