# Generated by Django 4.2.13 on 2024-06-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application_master", "0044_auto_20240618_1131"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0003_labellanguagetranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.PositiveIntegerField(
                        choices=[(2, "Active"), (0, "Inactive")], default=2
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("listing_order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("is_main", models.BooleanField(default=False)),
                ("btype_order", models.IntegerField(blank=True, null=True)),
                ("allow_multiple_address", models.BooleanField(default=False)),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Color"
                    ),
                ),
                ("is_training_type", models.BooleanField(default=False)),
                ("is_admin_type", models.BooleanField(default=False)),
                ("is_training_module", models.BooleanField(default=False)),
                ("is_activist_group", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="application_master.masterlookup",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="survey.beneficiarytype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.PositiveIntegerField(
                        choices=[(2, "Active"), (0, "Inactive")], default=2
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("listing_order", models.PositiveIntegerField(default=0)),
                (
                    "creation_key",
                    models.CharField(max_length=100, unique=True, verbose_name="UUID"),
                ),
                ("list_view", models.JSONField(default=dict)),
                ("profile_view", models.JSONField(default=dict)),
                ("json_answer_id", models.IntegerField(default=0)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("parent_beneficiary", models.IntegerField(blank=True, null=True)),
                ("address_1", models.IntegerField(default=0)),
                ("address_2", models.IntegerField(default=0)),
                ("address_3", models.IntegerField(default=0)),
                ("address_4", models.IntegerField(default=0)),
                ("address_5", models.IntegerField(db_index=True, default=0)),
                ("address_6", models.IntegerField(default=0)),
                ("address_7", models.IntegerField(default=0)),
                ("address_8", models.IntegerField(default=0)),
                (
                    "duplicate_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Approved"), (2, "Duplicate"), (3, "Rejected")],
                        null=True,
                    ),
                ),
                ("duplicate_marked_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Submitted for approval"),
                            (1, "Draft"),
                            (2, "Approved"),
                            (3, "Rejected"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_by_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficiary_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="survey.beneficiarytype",
                    ),
                ),
                (
                    "duplicate_marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
