# Generated by Django 4.2.13 on 2024-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0007_responseimportfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="responseimportfiles",
            name="processed_file",
            field=models.FileField(
                blank=True, null=True, upload_to="import-response/processed_files"
            ),
        ),
        migrations.AlterField(
            model_name="responseimportfiles",
            name="response_image",
            field=models.FileField(
                blank=True, null=True, upload_to="import-response/%Y/%m/%d"
            ),
        ),
    ]
