# Generated by Django 3.2.4 on 2021-12-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_data', '0001_initial'),
    ]

    operations = [
    migrations.RunSQL('drop function if exists replace_ids_with_text(integer,integer, character varying,boolean, integer, integer)'),
    migrations.RunSQL("""CREATE FUNCTION public.replace_ids_with_text(param_survey_id integer, param_in_type_qid integer, param_table_name character varying, param_partner_exists boolean, param_survey_type integer, param_ben_type integer) 
                            RETURNS JSONB
                                LANGUAGE plpgsql
                                AS $_$
                            DECLARE 
                                lcl_sql_query varchar := '';
                                lcl_loop_row RECORD;
                                lcl_counter integer := 1;
                                --lcl_key_where varchar := '';
                                lcl_group_cols varchar := '';
                                lcl_boundary_level_names varchar[];
                                lcl_boundarylevel_count integer := 0;
                                lcl_max_boundary_level_code integer := 0;
                                lcl_set_boundary_id_str varchar := '';
                                lcl_loop_set_boundary_id_str varchar := '';
                                lcl_t_start varchar := '';
                                lcl_t_choice_text varchar := '';
                                lcl_t_user_info varchar := '';
                                lcl_t_people_ai_boundary varchar := '';
                                lcl_t_ben_type varchar := '';
                                lcl_t_ben_type_2_70 varchar := '';
                                lcl_t_ben_type_3_71 varchar := '';
                                lcl_t_ben_type_11_73 varchar := '';
                                lcl_t_ben_type_11_73_1 varchar := '';
                                lcl_t_ben_type_13_181 varchar := '';
                                lcl_t_act_type varchar := '';
                                lcl_t_partner_info varchar := '';
                                lcl_t_project_info varchar := '';
                                lcl_t_cluster_boundary_info varchar := '';
                                lcl_t_aw_info varchar := '';
                            BEGIN 
                                lcl_t_start := CLOCK_TIMESTAMP();
                                if param_in_type_qid = 0 then
                                    select format('select concat(''response.'', a.id, case when gd_rows.id is null then '''' else ''.'' || gd_rows.id::text || ''.'' end, 
                                                    case when gd_cols.id is null then '''' else gd_cols.id::text end) as q_id, a.qtype 
                                        from survey_question a
                                        inner join survey_block b on a.block_id = b.id and b.survey_id = %s
                                        left outer join (select x1.id, x1.parent_id 
                                                    from survey_question x1
                                                    inner join survey_block x2 on x1.block_id = x2.id and x2.survey_id = %s
                                                    where parent_id is not null
                                                    and is_grid = false  order by x2.block_order, x1.question_order
                                        ) as gd_rows on gd_rows.parent_id = a.id
                                        left outer join (
                                                    select x1.id, x1.parent_id 
                                                    from survey_question x1
                                                    inner join survey_block x2 on x1.block_id = x2.id and x2.survey_id = %s
                                                    where parent_id is not null
                                                    and is_grid = true order by x2.block_order, x1.question_order
                                        )  as gd_cols on gd_rows.parent_id = gd_cols.parent_id 
                                        where qtype in (''R'',''S'',''C'') 
                                        and a.active != 0
                                        and a.parent_id is null',param_survey_id, param_survey_id, param_survey_id) into lcl_sql_query;
                                    -- select format(' %s.id = x1.id ', param_table_name) into lcl_key_where;
                                else 
                                    select format('select concat(''row_data.'', a.id) as q_id, a.qtype
                                        from survey_question a
                                        inner join survey_block b on a.block_id = b.id and b.survey_id = %s
                                        where qtype in (''R'',''S'',''C'')
                                        and a.active != 0
                                        and (a.id = %s or a.parent_id = %s )', param_survey_id, param_in_type_qid, param_in_type_qid) into lcl_sql_query;
                                    -- select format(' %s.response_id = x1.response_id and %s.row_id = x1.row_id ', param_table_name, param_table_name) into lcl_key_where;
                                end if;

                                -- RAISE NOTICE '--------1';
                                for lcl_loop_row IN EXECUTE lcl_sql_query
                                LOOP 
                                    -- RAISE NOTICE '--------1--%-%',lcl_loop_row.q_id,lcl_loop_row.qtype;
                                    if lcl_loop_row.qtype in ('R','S') then
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.text 
                                            from survey_choice x2 
                                            where %s."%s" = x2.id::text', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    elsif param_in_type_qid = 0 and lcl_loop_row.qtype in ('C') then 
                                        -- handle for checkbox type   
                                        create temp table if not exists export_choice_data_temp (
                                            id integer NOT NULL,
                                            row_id integer NOT NULL,
                                            choice_id varchar NOT NULL 
                                        );
                                        truncate table export_choice_data_temp;
                                        EXECUTE format( 'insert into export_choice_data_temp(id,row_id, choice_id)
                                                        (select id, 0, json_array_elements(replace(replace("%s",''"'',''''),'''''''','''')::json) as choice_id 
                                                        from %s
                                                        where %s."%s" is not null
                                                        )', lcl_loop_row.q_id, param_table_name, param_table_name, lcl_loop_row.q_id);
                                        EXECUTE format( 'update %s
                                            set "%s" = x.choice_text
                                            from  (select x1.id, x1.row_id, coalesce(array_to_json(array_agg(x2.text)),''[]''::json) as choice_text
                                                    from export_choice_data_temp x1
                                                    inner join survey_choice x2 on x1.choice_id::text = x2.id::text 
                                                    group by x1.id, x1.row_id
                                            ) as x
                                            where x.id = %s.id ', param_table_name, lcl_loop_row.q_id, param_table_name);
                                    elsif param_in_type_qid != 0 and lcl_loop_row.qtype in ('C') then 
                                        -- handle for checkbox type   
                                        create temp table if not exists export_choice_data_temp (
                                            id integer NOT NULL,
                                            row_id integer NOT NULL,
                                            choice_id varchar NOT NULL 
                                        );
                            --             select  response_id, row_id, "row_data.1360" as org,  (case when "row_data.1360"::text is null or "row_data.1360"::text = '0' then '"[]"'
                            --     when "row_data.1360" ~ '^"{0,1}[0-9]*"{0,1}$' then concat('"[',replace("row_data.1360" ,'"',''),']"')::text 
                            --     else "row_data.1360" end) as modified
                            -- from export_csv_343_1359_temp

                                        truncate table export_choice_data_temp;
                                        EXECUTE format( 'update %s
                                                            set "%s" = (case when "%s"::text is null or "%s"::text = ''0'' then ''"[]"''
                                                                when "%s" ~ ''^"{0,1}[0-9]*"{0,1}$'' then concat(''"['',replace("%s" ,''"'',''''),'']"'')::text
                                                                else "%s" end)
                                                            ', param_table_name, lcl_loop_row.q_id, lcl_loop_row.q_id, lcl_loop_row.q_id,
                                                        lcl_loop_row.q_id, lcl_loop_row.q_id, lcl_loop_row.q_id);
                                        EXECUTE format( 'insert into export_choice_data_temp(id,row_id, choice_id)
                                                        (select response_id, row_id, json_array_elements(replace(replace("%s",''"'',''''),'''''''','''')::json) as choice_id 
                                                        from %s
                                                        where %s."%s" is not null
                                                        )', lcl_loop_row.q_id, param_table_name, param_table_name, lcl_loop_row.q_id);
                                        EXECUTE format( 'update %s
                                            set "%s" = x.choice_text
                                            from  (select x1.id, x1.row_id, coalesce(array_to_json(array_agg(x2.text)),''[]''::json) as choice_text
                                                    from export_choice_data_temp x1
                                                    inner join survey_choice x2 on x1.choice_id::text = x2.id::text 
                                                    group by x1.id, x1.row_id
                                            ) as x
                                            where x.id = %s.response_id and x.row_id = %s.row_id', param_table_name, lcl_loop_row.q_id, param_table_name, param_table_name);
                                    end if;
                                end LOOP;
                                lcl_t_choice_text := CLOCK_TIMESTAMP();

                            --update user_id - user_id column is required only in the main excel sheet and not the intype questions sheets 
                            -- q_id will be 0 for the main sheet
                            if param_in_type_qid = 0 then
                                -- RAISE NOTICE '--------2';
                                EXECUTE format( 'update %s
                                        set user_id_ref_name = x2.username 
                                        from auth_user x2 where %s.user_id::text = x2.id::text', param_table_name, param_table_name);
                            end if;
                            lcl_t_user_info := CLOCK_TIMESTAMP();

                            if param_survey_id = 73 and param_in_type_qid = 0 then
                                -- beneficiary People - survey_id = 73
                                -- Include the reference data of the household - AI questions 640 in the People survey
                                -- RAISE NOTICE '--------2a';
                                EXECUTE format( 'update %s
                                    set "ai_question.616" = coalesce(x6.response->>''616''::text,''''),
                                    "ai_question.1219" = coalesce(x6.response->>''1219''::text,''''),
                                    "ai_question.1220" = coalesce(x6.response->>''1220''::text,''''),
                                    "ai_question.1237" = coalesce(x6.response->>''1237''::text,''''),
                                    "ai_question.1238" = coalesce(x6.response->>''1238''::text,''''),
                                    "ai_question.1239" = coalesce(x6.response->>''1239''::text,''''),
                                    "ai_question.626" = coalesce(sc626.text,''''),
                                    "ai_question.633.1" = coalesce(x6.response->''address''->''1''->''633''->>''1''::text,''''),
                                    "ai_question.633.2" = coalesce(x6.response->''address''->''1''->''633''->>''2''::text,''''),
                                    "ai_question.633.3" = coalesce(x6.response->''address''->''1''->''633''->>''3''::text,''''),
                                    "ai_question.633.4" = coalesce(x6.response->''address''->''1''->''633''->>''4''::text,''''),
                                    "ai_question.633.5" = coalesce(x6.response->''address''->''1''->''633''->>''5''::text,''''),
                                    "ai_question.633.6" = coalesce(x6.response->''address''->''1''->''633''->>''6''::text,''''),
                                    "ai_question.633.7" = coalesce(x6.response->''address''->''1''->''633''->>''7''::text,''''),
                                    "ai_question.633.8" = coalesce(x6.response->''address''->''1''->''633''->>''8''::text,''''),
                                    "address.1__id__" = (case when x6.response->''address''->''1''->''633''->>''1''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''1''::text)::integer else 0 end),
                                    "address.2__id__" = (case when x6.response->''address''->''1''->''633''->>''2''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''2''::text)::integer else 0 end),
                                    "address.3__id__" = (case when x6.response->''address''->''1''->''633''->>''3''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''3''::text)::integer else 0 end),
                                    "address.4__id__" = (case when x6.response->''address''->''1''->''633''->>''4''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''4''::text)::integer else 0 end),
                                    "address.5__id__" = (case when x6.response->''address''->''1''->''633''->>''5''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''5''::text)::integer else 0 end),
                                    "address.6__id__" = (case when x6.response->''address''->''1''->''633''->>''6''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''6''::text)::integer else 0 end),
                                    "address.7__id__" = (case when x6.response->''address''->''1''->''633''->>''7''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''7''::text)::integer else 0 end),
                                    "address.8__id__" = (case when x6.response->''address''->''1''->''633''->>''8''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''8''::text)::integer else 0 end)
                                from beneficiary_beneficiaryresponse x5  
                                inner join survey_jsonanswer x6 on x5.json_answer_id = x6.id
                                left outer join survey_choice sc626 on x6.response->>''626''::text = sc626.id::text
                                where (%s."response.640")::text = x5.id::text', param_table_name, param_table_name);
                                -- update people - Household data (633 of household) address widgets
                                select format('select concat(''ai_question.633.'',code) as q_id
                                        from masterdata_boundarylevel 
                                        order by code', param_survey_id) into lcl_sql_query;
                                for lcl_loop_row IN EXECUTE lcl_sql_query
                                LOOP 
                                    -- RAISE NOTICE '--------2a--%',lcl_loop_row.q_id;
                                    EXECUTE format( 'update %s
                                        set "%s" = x2.name 
                                        from masterdata_boundary x2 
                                        where %s."%s"::text = x2.id::text and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                end LOOP;  
                            end if;

                            lcl_t_people_ai_boundary := CLOCK_TIMESTAMP();

                            --update beneficiary_type and beneficiary reference name
                            -- survey_type 0 is beneficiary 1 is extended activity
                            -- in type questions of beneficiary type survey will not have ben.id fields 
                            if param_survey_type = 0 and param_in_type_qid = 0 then
                                EXECUTE format( 'update %s
                                    set "ben.id" = x2.id
                                    from beneficiary_beneficiaryresponse x2 
                                    where %s."creation_key" = x2.creation_key', param_table_name, param_table_name);
                                lcl_t_ben_type := CLOCK_TIMESTAMP();
                            elsif param_survey_type = 1 and param_ben_type != 0 then 
                                if param_in_type_qid = 0 and param_ben_type = 2 then
                                -- RAISE NOTICE '--------3';
                                -- beneficiary household - survey_id 70
                                    EXECUTE format( 'update %s
                                    set 
                                        "cluster.beneficiary_type_ref_name" = x3.name,
                                        "ben_type_question.616" = x4.response->>''616''::text,
                                        "ben_type_question.1219" = x4.response->>''1219''::text,
                                        "ben_type_question.1220" = x4.response->>''1220''::text,
                                        "ben_type_question.1237" = x4.response->>''1237''::text,
                                        "ben_type_question.1238" = x4.response->>''1238''::text,
                                        "ben_type_question.1239" = x4.response->>''1239''::text,
                                        "ben_type_question.626" = coalesce(sc626.text,''''),
                                        "ben_type_question.633.1" = x4.response->''address''->''1''->''633''->>''1''::text,
                                        "ben_type_question.633.2" = x4.response->''address''->''1''->''633''->>''2''::text,
                                        "ben_type_question.633.3" = x4.response->''address''->''1''->''633''->>''3''::text,
                                        "ben_type_question.633.4" = x4.response->''address''->''1''->''633''->>''4''::text,
                                        "ben_type_question.633.5" = x4.response->''address''->''1''->''633''->>''5''::text,
                                        "ben_type_question.633.6" = x4.response->''address''->''1''->''633''->>''6''::text,
                                        "ben_type_question.633.7" = x4.response->''address''->''1''->''633''->>''7''::text,
                                        "ben_type_question.633.8" = x4.response->''address''->''1''->''633''->>''8''::text,
                                        "address.1__id__" = (case when x4.response->''address''->''1''->''633''->>''1''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''1''::text)::integer else 0 end),
                                        "address.2__id__" = (case when x4.response->''address''->''1''->''633''->>''2''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''2''::text)::integer else 0 end),
                                        "address.3__id__" = (case when x4.response->''address''->''1''->''633''->>''3''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''3''::text)::integer else 0 end),
                                        "address.4__id__" = (case when x4.response->''address''->''1''->''633''->>''4''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''4''::text)::integer else 0 end),
                                        "address.5__id__" = (case when x4.response->''address''->''1''->''633''->>''5''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''5''::text)::integer else 0 end),
                                        "address.6__id__" = (case when x4.response->''address''->''1''->''633''->>''6''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''6''::text)::integer else 0 end),
                                        "address.7__id__" = (case when x4.response->''address''->''1''->''633''->>''7''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''7''::text)::integer else 0 end),
                                        "address.8__id__" = (case when x4.response->''address''->''1''->''633''->>''8''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''633''->>''8''::text)::integer else 0 end)
                                    from beneficiary_beneficiaryresponse x2 
                                    inner join beneficiary_beneficiarytype x3 on x2.beneficiary_type_id = x3.id
                                    inner join survey_jsonanswer x4 on x2.json_answer_id = x4.id
                                    left outer join survey_choice sc626 on x4.response->>''626''::text = sc626.id::text
                                    where %s."cluster.BeneficiaryResponse" = x2.creation_key ', param_table_name, param_table_name);
                                    -- update household (qid 633) address widgets
                                    select format('select concat(''ben_type_question.633.'',code) as q_id
                                            from masterdata_boundarylevel 
                                            order by code', param_survey_id) into lcl_sql_query;
                                    for lcl_loop_row IN EXECUTE lcl_sql_query
                                    LOOP 
                                        -- RAISE NOTICE '--------3--%',lcl_loop_row.q_id;
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.name 
                                            from masterdata_boundary x2 
                                            where %s."%s" = x2.id::text 
                                            and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    end LOOP;  
                                    lcl_t_ben_type_2_70 := CLOCK_TIMESTAMP();
                                elsif param_in_type_qid = 0 and param_ben_type = 3 then
                                    -- RAISE NOTICE '--------4';
                                -- beneficiary Group - survey_id = 71
                                    EXECUTE format( 'update %s
                                    set "cluster.beneficiary_type_ref_name" = x3.name,
                                        "ben_type_question.620" = x4.response->>''620''::text,
                                        "ben_type_question.622" = x622.text,
                                        "ben_type_question.940.1" = x4.response->''address''->''1''->''940''->>''1''::text,
                                        "ben_type_question.940.2" = x4.response->''address''->''1''->''940''->>''2''::text,
                                        "ben_type_question.940.3" = x4.response->''address''->''1''->''940''->>''3''::text,
                                        "ben_type_question.940.4" = x4.response->''address''->''1''->''940''->>''4''::text,
                                        "ben_type_question.940.5" = x4.response->''address''->''1''->''940''->>''5''::text,
                                        "ben_type_question.940.6" = x4.response->''address''->''1''->''940''->>''6''::text,
                                        "ben_type_question.940.7" = x4.response->''address''->''1''->''940''->>''7''::text,
                                        "ben_type_question.940.8" = x4.response->''address''->''1''->''940''->>''8''::text,
                                        "address.1__id__" = (case when x4.response->''address''->''1''->''940''->>''1''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''1''::text)::integer else 0 end),
                                        "address.2__id__" = (case when x4.response->''address''->''1''->''940''->>''2''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''2''::text)::integer else 0 end),
                                        "address.3__id__" = (case when x4.response->''address''->''1''->''940''->>''3''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''3''::text)::integer else 0 end),
                                        "address.4__id__" = (case when x4.response->''address''->''1''->''940''->>''4''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''4''::text)::integer else 0 end),
                                        "address.5__id__" = (case when x4.response->''address''->''1''->''940''->>''5''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''5''::text)::integer else 0 end),
                                        "address.6__id__" = (case when x4.response->''address''->''1''->''940''->>''6''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''6''::text)::integer else 0 end),
                                        "address.7__id__" = (case when x4.response->''address''->''1''->''940''->>''7''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''7''::text)::integer else 0 end),
                                        "address.8__id__" = (case when x4.response->''address''->''1''->''940''->>''8''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''940''->>''8''::text)::integer else 0 end)
                                    from beneficiary_beneficiaryresponse x2 
                                    inner join beneficiary_beneficiarytype x3 on x2.beneficiary_type_id = x3.id
                                    inner join survey_jsonanswer x4 on x2.json_answer_id = x4.id
                                    inner join survey_choice x622 on x622.id::text = x4.response->>''622''::text
                                    where %s."cluster.BeneficiaryResponse" = x2.creation_key ', param_table_name, param_table_name);
                                    -- update group village(qid 940) address widgets
                                    select format('select concat(''ben_type_question.940.'',code) as q_id
                                            from masterdata_boundarylevel 
                                            order by code', param_survey_id) into lcl_sql_query;
                                    for lcl_loop_row IN EXECUTE lcl_sql_query
                                    LOOP 
                                        -- RAISE NOTICE '--------4--%',lcl_loop_row.q_id;
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.name 
                                            from masterdata_boundary x2 
                                            where %s."%s" = x2.id::text 
                                            and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    end LOOP;  
                                    lcl_t_ben_type_3_71 := CLOCK_TIMESTAMP();
                                elsif param_in_type_qid = 0 and param_ben_type = 11 then
                                    -- RAISE NOTICE '--------5';
                                    -- beneficiary People - survey_id = 73
                                    -- Also include the reference data of the household - AI questions 640 in the People survey refers to household AW(633)
                                    -- Filter for people survey is based on the household address and not the people address question
                                        EXECUTE format( 'update %s
                                    set "cluster.beneficiary_type_ref_name" = x3.name,
                                        "ben_type_question.636" = x4.response->>''636''::text,
                                        "ben_type_question.1278.1" = x4.response->''address''->''1''->''1278''->>''1''::text,
                                        "ben_type_question.1278.2" = x4.response->''address''->''1''->''1278''->>''2''::text,
                                        "ben_type_question.1278.3" = x4.response->''address''->''1''->''1278''->>''3''::text,
                                        "ben_type_question.1278.4" = x4.response->''address''->''1''->''1278''->>''4''::text,
                                        "ben_type_question.1278.5" = x4.response->''address''->''1''->''1278''->>''5''::text,
                                        "ben_type_question.1278.6" = x4.response->''address''->''1''->''1278''->>''6''::text,
                                        "ben_type_question.1278.7" = x4.response->''address''->''1''->''1278''->>''7''::text,
                                        "ben_type_question.1278.8" = x4.response->''address''->''1''->''1278''->>''8''::text,
                                        "ben_type_question.616" = coalesce(x6.response->>''616''::text,''''),
                                        "ben_type_question.1219" = coalesce(x6.response->>''1219''::text,''''),
                                        "ben_type_question.1220" = coalesce(x6.response->>''1220''::text,''''),
                                        "ben_type_question.1237" = coalesce(x6.response->>''1237''::text,''''),
                                        "ben_type_question.1238" = coalesce(x6.response->>''1238''::text,''''),
                                        "ben_type_question.1239" = coalesce(x6.response->>''1239''::text,''''),
                                        "ben_type_question.626" = coalesce(sc626.text,''''),
                                        "ben_type_question.633.1" = coalesce(x6.response->''address''->''1''->''633''->>''1''::text,''''),
                                        "ben_type_question.633.2" = coalesce(x6.response->''address''->''1''->''633''->>''2''::text,''''),
                                        "ben_type_question.633.3" = coalesce(x6.response->''address''->''1''->''633''->>''3''::text,''''),
                                        "ben_type_question.633.4" = coalesce(x6.response->''address''->''1''->''633''->>''4''::text,''''),
                                        "ben_type_question.633.5" = coalesce(x6.response->''address''->''1''->''633''->>''5''::text,''''),
                                        "ben_type_question.633.6" = coalesce(x6.response->''address''->''1''->''633''->>''6''::text,''''),
                                        "ben_type_question.633.7" = coalesce(x6.response->''address''->''1''->''633''->>''7''::text,''''),
                                        "ben_type_question.633.8" = coalesce(x6.response->''address''->''1''->''633''->>''8''::text,''''),
                                        "address.1__id__" = (case when x6.response->''address''->''1''->''633''->>''1''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''1''::text)::integer else 0 end),
                                        "address.2__id__" = (case when x6.response->''address''->''1''->''633''->>''2''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''2''::text)::integer else 0 end),
                                        "address.3__id__" = (case when x6.response->''address''->''1''->''633''->>''3''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''3''::text)::integer else 0 end),
                                        "address.4__id__" = (case when x6.response->''address''->''1''->''633''->>''4''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''4''::text)::integer else 0 end),
                                        "address.5__id__" = (case when x6.response->''address''->''1''->''633''->>''5''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''5''::text)::integer else 0 end),
                                        "address.6__id__" = (case when x6.response->''address''->''1''->''633''->>''6''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''6''::text)::integer else 0 end),
                                        "address.7__id__" = (case when x6.response->''address''->''1''->''633''->>''7''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''7''::text)::integer else 0 end),
                                        "address.8__id__" = (case when x6.response->''address''->''1''->''633''->>''8''::text ~ ''^[1-9][0-9]*$'' then (x6.response->''address''->''1''->''633''->>''8''::text)::integer else 0 end)
                                    from beneficiary_beneficiaryresponse x2 
                                    inner join beneficiary_beneficiarytype x3 on x2.beneficiary_type_id = x3.id
                                    inner join survey_jsonanswer x4 on x2.json_answer_id = x4.id
                                    left outer join beneficiary_beneficiaryresponse x5 on (x4.response->>''640'')::text = x5.id::text
                                    left outer join survey_jsonanswer x6 on x5.json_answer_id = x6.id
                                    left outer join survey_choice sc626 on x6.response->>''626''::text = sc626.id::text
                                    where %s."cluster.BeneficiaryResponse" = x2.creation_key', param_table_name, param_table_name);
                                    -- update people (qid 1278) address widgets
                                    select format('select concat(''ben_type_question.1278.'',code) as q_id
                                            from masterdata_boundarylevel 
                                            order by code', param_survey_id) into lcl_sql_query;
                                    for lcl_loop_row IN EXECUTE lcl_sql_query
                                    LOOP 
                                        -- RAISE NOTICE '--------5--%',lcl_loop_row.q_id;
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.name 
                                            from masterdata_boundary x2 
                                            where  %s."%s" = x2.id::text and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    end LOOP;  
                                    lcl_t_ben_type_11_73 := CLOCK_TIMESTAMP();
                                    -- update people - Household data (qid 640 of people - 633 of household) address widgets
                                    select format('select concat(''ben_type_question.633.'',code) as q_id
                                            from masterdata_boundarylevel 
                                            order by code', param_survey_id) into lcl_sql_query;
                                    for lcl_loop_row IN EXECUTE lcl_sql_query
                                    LOOP 
                                        -- RAISE NOTICE '--------5a--%',lcl_loop_row.q_id;
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.name 
                                            from masterdata_boundary x2
                                            where %s."%s" = x2.id::text and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    end LOOP;  
                                    lcl_t_ben_type_11_73_1 := CLOCK_TIMESTAMP();
                                elsif param_in_type_qid = 0 and param_ben_type = 13 then
                                    -- RAISE NOTICE '--------6';
                                -- beneficiary Institution - survey_id = 181
                                    EXECUTE format( 'update %s
                                    set "cluster.beneficiary_type_ref_name" = x3.name,
                                        "ben_type_question.944" = x4.response->>''944''::text,
                                        "ben_type_question.946" = x946.text,
                                        "ben_type_question.945" = x4.response->>''945''::text,
                                        "ben_type_question.1288.1" = x4.response->''address''->''1''->''1288''->>''1''::text,
                                        "ben_type_question.1288.2" = x4.response->''address''->''1''->''1288''->>''2''::text,
                                        "ben_type_question.1288.3" = x4.response->''address''->''1''->''1288''->>''3''::text,
                                        "ben_type_question.1288.4" = x4.response->''address''->''1''->''1288''->>''4''::text,
                                        "ben_type_question.1288.5" = x4.response->''address''->''1''->''1288''->>''5''::text,
                                        "ben_type_question.1288.6" = x4.response->''address''->''1''->''1288''->>''6''::text,
                                        "ben_type_question.1288.7" = x4.response->''address''->''1''->''1288''->>''7''::text,
                                        "ben_type_question.1288.8" = x4.response->''address''->''1''->''1288''->>''8''::text,
                                        "address.1__id__" = (case when x4.response->''address''->''1''->''1288''->>''1''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''1''::text)::integer else 0 end),
                                        "address.2__id__" = (case when x4.response->''address''->''1''->''1288''->>''2''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''2''::text)::integer else 0 end),
                                        "address.3__id__" = (case when x4.response->''address''->''1''->''1288''->>''3''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''3''::text)::integer else 0 end),
                                        "address.4__id__" = (case when x4.response->''address''->''1''->''1288''->>''4''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''4''::text)::integer else 0 end),
                                        "address.5__id__" = (case when x4.response->''address''->''1''->''1288''->>''5''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''5''::text)::integer else 0 end),
                                        "address.6__id__" = (case when x4.response->''address''->''1''->''1288''->>''6''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''6''::text)::integer else 0 end),
                                        "address.7__id__" = (case when x4.response->''address''->''1''->''1288''->>''7''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''7''::text)::integer else 0 end),
                                        "address.8__id__" = (case when x4.response->''address''->''1''->''1288''->>''8''::text ~ ''^[1-9][0-9]*$'' then (x4.response->''address''->''1''->''1288''->>''8''::text)::integer else 0 end)
                                    from beneficiary_beneficiaryresponse x2 
                                    inner join beneficiary_beneficiarytype x3 on x2.beneficiary_type_id = x3.id
                                    inner join survey_jsonanswer x4 on x2.json_answer_id = x4.id
                                    inner join survey_choice x946 on x946.id::text = x4.response->>''946''::text
                                    where %s."cluster.BeneficiaryResponse" = x2.creation_key ', param_table_name, param_table_name);
                                    -- update institution block(qid 1288) address widgets
                                    select format('select concat(''ben_type_question.1288.'',code) as q_id
                                            from masterdata_boundarylevel 
                                            order by code', param_survey_id) into lcl_sql_query;
                                    for lcl_loop_row IN EXECUTE lcl_sql_query
                                    LOOP 
                                        -- RAISE NOTICE '--------6--%',lcl_loop_row.q_id;
                                        EXECUTE format( 'update %s
                                            set "%s" = x2.name 
                                            from masterdata_boundary x2 
                                            where %s."%s" = x2.id::text and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    end LOOP;  
                                    lcl_t_ben_type_13_181 := CLOCK_TIMESTAMP();
                                elsif param_in_type_qid = 0 then
                                    -- RAISE NOTICE '--------7';
                                    EXECUTE format( 'update %s
                                        set "cluster.beneficiary_type_ref_name" = x3.name
                                        from beneficiary_beneficiaryresponse x2 
                                        inner join beneficiary_beneficiarytype x3 on x2.beneficiary_type_id = x3.id
                                        where %s."cluster.BeneficiaryResponse" = x2.creation_key ', param_table_name, param_table_name);
                                    lcl_t_act_type := CLOCK_TIMESTAMP();
                                end if;
                            end if;

                            -- update partner_details
                            -- only if the partners are managed in the program and if the data is for the main sheet
                            if param_partner_exists = true and param_in_type_qid = 0 then
                                -- RAISE NOTICE '--------8';
                                EXECUTE format( 'update %s
                                    set "cluster.partner_id_ref_name" = x2.name
                                    from partner_partner x2 
                                    where %s."cluster.partner_id" = x2.id::text ', param_table_name, param_table_name);
                            end if;

                            lcl_t_partner_info := CLOCK_TIMESTAMP();

                            if param_in_type_qid = 0 and param_survey_type = 1 then
                                -- update project details
                                -- RAISE NOTICE '--------9';
                                EXECUTE format( 'update %s
                                    set "cluster.project_id_ref_name" = x2.name
                                    from projectmanagement_project x2 
                                    where %s."cluster.project_id"::text = x2.id::text and %s."cluster.project_id" is not null and %s."cluster.project_id"::text ~ ''^[0-9]+$'' ', param_table_name, param_table_name, param_table_name, param_table_name);

                                lcl_t_project_info := CLOCK_TIMESTAMP();
                                -- update cluster Boundary information - boundary level, state, region, district, cluster, block, gp, village, hamlet
                                -- RAISE NOTICE '--------10';
                                EXECUTE format( 'update %s
                                    set "cluster.boundary_level" = x3.name
                                    from masterdata_boundary x2
                                    inner join masterdata_boundarylevel x3 on x2.boundary_level_type_id = x3.id
                                    where %s."cluster.Boundary"::integer = x2.id ', param_table_name, param_table_name);
                                EXECUTE format('select max(c.code) 
                                                from %s a 
                                                inner join masterdata_boundary b on a."cluster.Boundary"::integer = b.id 
                                                inner join masterdata_boundarylevel c on c.id = b.boundary_level_type_id', param_table_name) into lcl_max_boundary_level_code;
                                lcl_boundary_level_names := Array(select lower(name) as name 
                                                from masterdata_boundarylevel 
                                                where code <= lcl_max_boundary_level_code order by code desc);
                                -- RAISE NOTICE 'Array: %', lcl_boundary_level_names;
                                lcl_boundarylevel_count := array_length(lcl_boundary_level_names,1);
                                -- RAISE NOTICE 'Array: %', lcl_boundary_level_names;
                                if lcl_boundary_level_names is not null and lcl_boundarylevel_count > 0 then
                                    -- when ben_type is 0 then the cluster boundary will be used as the filter and hence the __id__ fields will be included in the table
                                    -- these fields have to be updated with the id value of the boundary hierarcy
                                    if param_ben_type = 0 then
                                        lcl_set_boundary_id_str := ',"address.%s__id__" = x2.id,';
                                    else 
                                        lcl_set_boundary_id_str := ',';
                                    end if;
                                    -- RAISE NOTICE '--------11--%',lcl_set_boundary_id_str;
                                    FOR counter IN 1..lcl_boundarylevel_count LOOP
                                        if lcl_set_boundary_id_str != '' then
                                            lcl_loop_set_boundary_id_str := format(lcl_set_boundary_id_str, counter);
                                        end if;
                                        -- RAISE NOTICE '--------11a--%',lcl_loop_set_boundary_id_str;
                                        if counter = 1 then
                                            EXECUTE format( 'update %s
                                                set "cluster.boundary_%s" = x2.name
                                                    %s                    
                                                    "cluster.boundary_%s" = x2.parent_id
                                                from masterdata_boundary x2 
                                                where  %s."cluster.Boundary"::integer = x2.id ', param_table_name, lcl_boundary_level_names[(counter)], lcl_loop_set_boundary_id_str, lcl_boundary_level_names[(counter+1)], param_table_name);
                                            -- RAISE NOTICE 'Q1: %s', format( 'update %s
                                            --     set "cluster.boundary_%s" = x2.name
                                            --         %s                    
                                            --         "cluster.boundary_%s" = x2.parent_id
                                            --     from masterdata_boundary x2 
                                            --     where  %s."cluster.Boundary"::integer = x2.id ', param_table_name, lcl_boundary_level_names[(counter)], lcl_loop_set_boundary_id_str, lcl_boundary_level_names[(counter+1)], param_table_name);
                                        elsif counter = lcl_boundarylevel_count then
                                            -- RAISE NOTICE '--------11b--%',left(lcl_loop_set_boundary_id_str,-1);
                                            EXECUTE format( 'update %s
                                                set "cluster.boundary_%s" = x2.name
                                                %s
                                                from masterdata_boundary x2 
                                                where %s."cluster.boundary_%s" = x2.id::text ', param_table_name, lcl_boundary_level_names[(counter)], left(lcl_loop_set_boundary_id_str,-1), param_table_name, lcl_boundary_level_names[(counter)]);
                                            -- RAISE NOTICE 'Q2: %s', format( 'update %s
                                            --     set "cluster.boundary_%s" = x2.name
                                            --     %s
                                            --     from masterdata_boundary x2 
                                            --     where %s."cluster.boundary_%s" = x2.id::text ', param_table_name, lcl_boundary_level_names[(counter)], left(lcl_loop_set_boundary_id_str,-1), param_table_name, lcl_boundary_level_names[(counter)]);
                                        else 
                                            EXECUTE format( 'update %s
                                                set "cluster.boundary_%s" = x2.name
                                                    %s
                                                    "cluster.boundary_%s" = x2.parent_id
                                                from masterdata_boundary x2 
                                                where %s."cluster.boundary_%s" = x2.id::text ', param_table_name, lcl_boundary_level_names[(counter)], lcl_loop_set_boundary_id_str, lcl_boundary_level_names[(counter+1)], param_table_name,lcl_boundary_level_names[(counter)]);
                                            -- RAISE NOTICE 'Q3: %s', format( 'update %s
                                            --     set "cluster.boundary_%s" = x2.name
                                            --         %s
                                            --         "cluster.boundary_%s" = x2.parent_id
                                            --     from masterdata_boundary x2 
                                            --     where %s."cluster.boundary_%s" = x2.id::text ', param_table_name, lcl_boundary_level_names[(counter)], lcl_loop_set_boundary_id_str, lcl_boundary_level_names[(counter+1)], param_table_name,lcl_boundary_level_names[(counter)]);
                                        end if;
                                    END LOOP;
                                end if;
                                lcl_t_cluster_boundary_info := CLOCK_TIMESTAMP();
                            end if;

                            --- update address widgets
                                -- RAISE NOTICE '--------12';
                                select format('select concat(''response.address.1.'', a.id, ''.'',c.code) as q_id
                                        from survey_question a
                                        inner join survey_block b on a.block_id = b.id and b.survey_id = %s
                                        inner join masterdata_boundarylevel c on true
                                        where a.qtype = ''AW''
                                        and a.active != 0 
                                        order by c.code', param_survey_id) into lcl_sql_query;
                                --select format(' %s.id = x1.id ', param_table_name) into lcl_key_where;
                                --select format(' %s.sl_no = x1.sl_no ', param_table_name) into lcl_key_where;
                                -- Filter for people survey is based on the household address and not the people address question
                                if param_survey_id != 73 then
                                    lcl_set_boundary_id_str := ',"address.%s__id__" = coalesce(x2.id,''0'')::int';
                                else 
                                    lcl_set_boundary_id_str := '';
                                end if;
                                lcl_counter := 1;
                                for lcl_loop_row IN EXECUTE lcl_sql_query
                                LOOP 
                                    if lcl_set_boundary_id_str != '' then
                                        lcl_loop_set_boundary_id_str := format(lcl_set_boundary_id_str, lcl_counter);
                                    end if;
                                    -- RAISE NOTICE '--------12--%',lcl_loop_row.q_id;
                                    EXECUTE format( 'update %s
                                    set "%s" = x2.name
                                    %s
                                    from masterdata_boundary x2 
                                    where %s."%s" = x2.id::text and %s."%s" is not null and %s."%s" != ''''', param_table_name, lcl_loop_row.q_id, lcl_loop_set_boundary_id_str, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id, param_table_name, lcl_loop_row.q_id);
                                    lcl_counter := lcl_counter + 1;
                                end LOOP;  
                                lcl_t_aw_info := CLOCK_TIMESTAMP();
                                return jsonb_build_object('1-lcl_t_start', lcl_t_start, '2-lcl_t_choice_text', lcl_t_choice_text, '3-lcl_t_user_info', lcl_t_user_info,
                                    '4-lcl_t_people_ai_boundary', lcl_t_people_ai_boundary, '5-lcl_t_ben_type', lcl_t_ben_type, '5a-lcl_t_ben_type_2_70', lcl_t_ben_type_2_70, 
                                    '5b-lcl_t_ben_type_3_71', lcl_t_ben_type_3_71, '5c-lcl_t_ben_type_11_73', lcl_t_ben_type_11_73, '5d-lcl_t_ben_type_11_73_1', lcl_t_ben_type_11_73_1, 
                                    '5e-lcl_t_ben_type_13_181', lcl_t_ben_type_13_181, '5f-lcl_t_act_type', lcl_t_act_type, '6-lcl_t_partner_info', lcl_t_partner_info,
                                    '7-lcl_t_project_info',lcl_t_project_info, '8-lcl_t_cluster_boundary_info',lcl_t_cluster_boundary_info,
                                    '9-lcl_t_aw_info',lcl_t_aw_info);
                            END;
                            $_$"""),
]
